[server]
runOnSave = true
enableStaticServing = false

[client]
showSidebarNavigation = false

[theme]
base="dark"

# Primary accent for interactive elements
primaryColor = '#008768'

# Background color for the main content area, #273346
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F9F9F9'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

